import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../src/data/monetaryContracts');
const names = ['common', 'authority-graph', 'savings-policy', 'subject', 'asset', 'index', 'shard', 'namespace'];
const schemas = Object.fromEntries(names.map(name => [name.replaceAll('-', '_'), JSON.parse(fs.readFileSync(path.join(root, 'schemas', `${name}.schema.json`), 'utf8'))]));
const eligibilityNames = ['subject', 'asset', 'index', 'shard', 'namespace'];
const eligibilitySchemas = Object.fromEntries(eligibilityNames.map(name => [name, JSON.parse(fs.readFileSync(path.join(root, '../eligibilityContracts', `executable-${name}-v2.schema.json`), 'utf8'))]));
// Lossless structural sharing only. No schema keys, annotations or constraints removed.
const counts = new Map();
function scan(value) {
  const text = JSON.stringify(value);
  if (text.length >= 8) counts.set(text, (counts.get(text) ?? 0) + 1);
  if (Array.isArray(value)) value.forEach(scan);
  else if (value && typeof value === 'object') Object.entries(value).forEach(([key, child]) => { scan(key); scan(child); });
}
Object.values(schemas).forEach(scan);
Object.values(eligibilitySchemas).forEach(scan);
const constants = [], aliases = new Map();
function emit(value) {
  const key = JSON.stringify(value), count = counts.get(key) ?? 0, shared = count > 1 && (count - 1) * (key.length - 5) > 20;
  if (shared && aliases.has(key)) return aliases.get(key);
  const text = Array.isArray(value) ? `[${value.map(emit).join(',')}]` : value && typeof value === 'object' ? `{${Object.entries(value).map(([k, v]) => { const field = emit(k); return `${field.startsWith('"') ? field : `[${field}]`}:${emit(v)}`; }).join(',')}}` : JSON.stringify(value);
  if (!shared) return text;
  const name = `s${constants.length}`; aliases.set(key, name); constants.push(`const ${name}: any = ${text};`); return name;
}
const body = Object.entries(schemas).map(([key, value]) => `${JSON.stringify(key)}:${emit(value)}`).join(',');
const eligibilityBody = Object.entries(eligibilitySchemas).map(([key, value]) => `${JSON.stringify(key)}:${emit(value)}`).join(',');
const output = `// Generated by mobile/scripts/generate-monetary-schemas.mjs. Do not edit.\n// Lossless frozen v2/v3 schema graphs; shared nodes are read-only.\n${constants.join('\n')}\nconst schemas = {${body}};\nexport const eligibilitySchemas = {${eligibilityBody}};\nexport default schemas;\n`;
const destination = path.join(root, 'runtimeSchemas.ts');
if (process.argv.includes('--check')) {
  if (fs.readFileSync(destination, 'utf8') !== output) throw new Error('Monetary runtime schemas are stale');
} else fs.writeFileSync(destination, output, 'utf8');
console.log(JSON.stringify({ frozenCompactBytes: Buffer.byteLength(JSON.stringify({ schemas, eligibilitySchemas })), generatedBytes: Buffer.byteLength(output), sharedNodes: constants.length }));
