import { gunzipSync, strFromU8 } from 'fflate';

import { decryptAsset, isEncryptedAsset, payloadKeyId } from '../src/lib/payloadCrypto';

// Interop vectors generated by the Pi-side payload_crypto.py (Phase A):
//   key = bytes(range(32)); plain = gzip('{"v":1,"msg":"interop"}', mtime=0)
const KEY_HEX = '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f';
const BLOB_HEX =
  '41524531dd66386e60d5584ba7aa4ab9afb5b8131cf2ab514ed7d5e76fa1ab82a20b8f44b22d9a66822d9ef8bb7e0094a49a6e552251a3f1f05a67f2a211f6e1f61d2e8af502b41322fd4d';

function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i += 1) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

describe('payloadCrypto', () => {
  it('decrypts a Pi-encrypted asset (cross-language vector)', () => {
    const plainGz = decryptAsset(fromHex(BLOB_HEX), KEY_HEX);
    const json = JSON.parse(strFromU8(gunzipSync(plainGz)));
    expect(json).toEqual({ v: 1, msg: 'interop' });
  });

  it('derives the same key id as the Pi', () => {
    expect(payloadKeyId(KEY_HEX)).toBe('f7c55ca3');
  });

  it('detects the ARE1 magic', () => {
    expect(isEncryptedAsset(fromHex(BLOB_HEX))).toBe(true);
    expect(isEncryptedAsset(Uint8Array.from([0x1f, 0x8b, 0x08, 0x00, 0x00]))).toBe(false);
  });

  it('fails closed on a wrong key', () => {
    const wrong = '00'.repeat(32);
    expect(() => decryptAsset(fromHex(BLOB_HEX), wrong)).toThrow();
  });

  it('rejects tampered ciphertext', () => {
    const tampered = fromHex(BLOB_HEX);
    tampered[tampered.length - 1] ^= 0x01;
    expect(() => decryptAsset(tampered, KEY_HEX)).toThrow();
  });

  it('explains a missing key configuration', () => {
    expect(() => decryptAsset(fromHex(BLOB_HEX), '')).toThrow(/no decryption key/);
  });
});
